'use client';
import { CASE_STUDIES, COMPLIANCE_ITEMS, FAQS, RESOURCES } from '@/lib/constants';
import { SectionLabel } from '@/components/ui/SectionLabel';

export function CaseStudiesSection(){return <section className='mx-auto max-w-7xl px-6 py-20'><SectionLabel>FEATURED CASE STUDIES</SectionLabel><h2 className='text-4xl font-bold text-white'>Measured outcomes from enterprise delivery</h2><div className='mt-8 grid gap-5 lg:grid-cols-3'>{CASE_STUDIES.map((c)=><article key={c.client} className='rounded-2xl border border-slate-700 bg-[#0f1420] p-6'><p className='text-xs uppercase tracking-widest text-cyan-300'>{c.outcome}</p><h3 className='mt-2 text-lg text-white'>{c.client}</h3><p className='mt-2 text-sm font-semibold text-cyan-200'>{c.metric}</p><p className='mt-3 text-sm text-slate-400'>{c.summary}</p></article>)}</div></section>}

export function ComplianceSection(){return <section className='bg-[#0b111c] px-6 py-20'><div className='mx-auto max-w-7xl'><SectionLabel>SECURITY & COMPLIANCE</SectionLabel><h2 className='text-4xl font-bold text-white'>Governance-ready delivery standards</h2><div className='mt-8 grid gap-4 md:grid-cols-2'>{COMPLIANCE_ITEMS.map((c)=><article key={c.title} className='rounded-2xl border border-slate-700 bg-[#0f1420] p-6'><h3 className='text-lg text-cyan-300'>{c.title}</h3><p className='mt-2 text-sm text-slate-400'>{c.detail}</p></article>)}</div></div></section>}

export function FaqSection(){return <section className='mx-auto max-w-7xl px-6 py-20'><SectionLabel>FAQ FOR DECISION MAKERS</SectionLabel><h2 className='text-4xl font-bold text-white'>Answers for CTO, CISO, and IT leadership</h2><div className='mt-8 space-y-4'>{FAQS.map((f)=><article key={f.q} className='rounded-2xl border border-slate-700 bg-[#0f1420] p-6'><h3 className='text-lg text-white'>{f.q}</h3><p className='mt-2 text-sm text-slate-400'>{f.a}</p></article>)}</div></section>}

export function ResourcesSection(){return <section className='mx-auto max-w-7xl px-6 py-20'><SectionLabel>INSIGHTS & RESOURCES</SectionLabel><h2 className='text-4xl font-bold text-white'>Frameworks your team can apply immediately</h2><div className='mt-8 grid gap-5 md:grid-cols-3'>{RESOURCES.map((r)=><article key={r.title} className='rounded-2xl border border-slate-700 bg-[#0f1420] p-6'><p className='text-xs uppercase tracking-widest text-cyan-300'>{r.type}</p><h3 className='mt-2 text-lg text-white'>{r.title}</h3><p className='mt-2 text-sm text-slate-400'>{r.summary}</p></article>)}</div></section>}
